apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  annotations:
    dcat.data.nav.no/title: "Utgatt forhåndsvarsel om avslag på sykepenger for arbeidsuforhet sykmeldte personer"
    dcat.data.nav.no/description: >-
      Topic inneholder informasjon om et forhåndsvarsel der svarfrist har gatt ut.
  name: arbeidsuforhet-expired-forhandsvarsel
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  pool: {{ kafkaPool }}
  config:
    cleanupPolicy: delete
    minimumInSyncReplicas: 1
    partitions: 4
    replication: 3
    retentionBytes: -1  # -1 means unlimited
    retentionHours: -1  # -1 means unlimited
  acl:
    - team: teamsykefravr
      application: isarbeidsuforhet
      access: readwrite
    - team: teamsykefravr
      application: ispersonoppgave
      access: read
